import { Sinc } from "@sincronia/types";
import { defaultTableOptions } from "./tableOptions";
const excludes = [
  "sys_scope_privilege",
  "sys_dictionary",
  "sys_impex_entry",
  "sys_security_acl",
  "sys_transform_map",
  "sys_ui_policy",
  "sys_ui_list_control",
  "sys_relationship",
  "sys_report",
  "item_option_new",
  "sys_process_flow",
  "content_block_programmatic",
  "sp_instance",
  "sys_transform_script",
  "sc_category",
  "sysrule_view",
  "sc_cat_item",
  "sysevent_in_email_action",
  "sys_navigator",
  "sys_transform_entry",
  "metric_definition",
  "content_block_lists",
  "content_block_detail",
  "sp_portal",
  "sc_cat_item_producer",
  "sys_impex_map",
];

const includes = [
  "sysauto_script",
  "sys_extension_point",
  "sys_script",
  "sys_script_include",
  "sys_ui_action",
  "sys_ws_operation",
  "sysevent_email_action",
  "sys_script_client",
  "sys_ui_page",
  "catalog_script_client",
  "sp_instance_menu",
  "sp_instance_vlist",
  "sp_page",
  "sysevent_script_action",
  "sys_ui_macro",
  "sys_ui_script",
  "sys_sg_data_item",
  "sys_sg_write_back_action_item",
  "sys_script_fix",
  "sysevent_email_template",
  "sc_cat_item_content",
  "sp_widget",
  "sys_script_email",
  "catalog_ui_policy",
  "cmn_map_page",
  "ecc_agent_script_include",
  "scheduled_import_set",
  "sp_angular_provider",
  "sp_css",
  "sp_header_footer",
  "sp_ng_template",
  "sys_data_source",
  "sys_processor",
  "sys_ui_context_menu",
  "sys_ui_list_control_embedded",
  "sys_decision_input",
  "sys_email_client_template",
  "sys_recipient_qualifier",
  "sys_navigator",
  "content_css",
];

const tableOptions: Sinc.ITableOptionsMap = defaultTableOptions;
const defaultOptions = { includes, excludes, tableOptions };
export default defaultOptions;
